name: run-ui-tests

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    # Set up necessary services
    services:
      selenium:
        image: selenium/standalone-chrome
        options: --shm-size=2gb
        ports:
          - 4444:4444

    steps:
      - name: checkout-repo
        uses: actions/checkout@v3

      - name: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: install-dependencies
        run: npm install

      # Start HTTP server to serve the project files
      - name: Start HTTP server
        run: |
          npm install -g http-server
          nohup http-server -p 8099 -c-1 . &

      # Wait for server to be ready
      - name: Wait for server to be available
        run: npx wait-on --timeout 15000 http://localhost:8099

      # Confirm the server is still running
      - name: Confirm server status
        run: curl -I http://localhost:8099

      - name: run-tests
        env:
          SELENIUM_URL: http://localhost:4444/wd/hub  # Selenium server URL
          SERVER_URL: http://localhost:8099  # HTTP server URL
        run: npm run test

      - name: Upload failure screenshot as artifact
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: screenshot
          path: fail_screenshot.png
