name: run-ui-tests

on:
  pull_request:
    branches:
      - main  
  workflow_dispatch:  

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    # Set up necessary services
    services:
      selenium:
        image: selenium/standalone-chrome  
        ports:
          - 4444:4444

    steps:
      - name: checkout-repo
        uses: actions/checkout@v3

      - name: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'  

      - name: install-dependencies
        run: npm install 

      - name: run-tests
        env:
          SELENIUM_URL: http://localhost:4444/wd/hub  # Selenium server URL
        run: npm test

      - name: Upload screenshot as artifact
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: screenshot
          path: fail_screenshot.png