name: run-ui-tests

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    # Set up necessary services
    services:
      selenium:
        image: selenium/standalone-chrome
        options: --shm-size=2gb
        ports:
          - 4444:4444

    steps:
      - name: checkout-repo
        uses: actions/checkout@v3

      - name: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: install-dependencies
        run: npm install

      # Start HTTP server to serve the project files
      - name: Start HTTP server
        run: |
          npm install -g http-server
          nohup http-server -a 0.0.0.0 -p 8099 -c-1 . &

      - name: Wait for HTTP Server
        run: |
          echo "Waiting for HTTP server at http://host.docker.internal:8099..."
          npx wait-on --timeout 60000 http://host.docker.internal:8099
          curl -I http://host.docker.internal:8099


      - name: Confirm server status
        run: |
          for i in {1..5}; do
            if curl -I http://127.0.0.1:8099; then
              echo "Server is up!"
              break
            else
              echo "Waiting for server..."
              sleep 5
            fi
          done

      - name: Check Selenium Server Status
        run: |
          echo "Waiting for Selenium server at http://localhost:4444..."
          for i in {1..5}; do
            if curl -s http://localhost:4444/wd/hub/status | grep -q '"ready":true'; then
              echo "Selenium server is ready!"
              break
            else
              echo "Waiting for Selenium server..."
              sleep 5
            fi
          done
          curl -s http://localhost:4444/wd/hub/status

      - name: DEBUG - Check Running Processes
        run: ps aux

      - name: DEBUG - List Open Network Ports
        run: netstat -tuln

      - name: run-tests
        env:
          SELENIUM_URL: http://localhost:4444/wd/hub  # Selenium server URL
          SERVER_URL: http://host.docker.internal:8099            # HTTP server URL
        run: npm test

      - name: Upload failure screenshot as artifact
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: screenshot
          path: fail_screenshot.png
